### ISSUE TITLE
support multiple sheets in a page

### ISSUE THREAD

**Issue by roasted-potatoe** [radiatoryang/bobbin#4]
Being able to choose the sheet of the spreadsheet would be a nice feature to have.

**Comment by radiatoryang** [comment]
looked into this; it looks like Google Sheets CSV export relies on a currently selected sheet. which gets defined as a "gid" variable in the URL string... and the GID is a bunch of randomly assigned digits, so Bobbin cannot predict or derive a GID from a document ID

so Bobbin would have to be able to extract the GID from the URL string (supplied by the user) and then insert that GID var in the export URL too, as well as modify the UI to show that a specific sheet was used... the user would still have to create a new entry for each sheet, unfortunately, due to limitations in Google Sheets' CSV export

a more robust solution: implement something like [ExcelDataReader](https://github.com/ExcelDataReader/ExcelDataReader) and export the .XLSX from Google Docs instead, which means we can process any / all sheets at once... however, that makes this tool considerably heavier / opens a big can of worms about how to support .XLSX properly

- I'm currently really busy with other stuff, but I can come back to this in late April or May
- in the meantime, anyone reading this is free to submit a PR for the "GID" solution I mentioned in the first 2 paragraphs

**Comment by ssmasrour** [comment]
TBH, your great tool only lacks this feature. Waiting to hearing that this plugin is updated. cheers

**Comment by ssmasrour** [comment]
Fixed on fork "https://github.com/ssmasrour/Google-Sheets-to-Unity"

**Comment by radiatoryang** [comment]
thanks for the PR!
